 /* ************************************************************************
   Copyright: 2026
   AUTO-GENERATED by scripts/lucide-registry.mjs — do not edit by hand.
   Run: npm run lucide:registry
************************************************************************ */

qx.Class.define("myapp.util.LucideRegistry", {
  type: "static",

  statics: {
    /** Qooxdoo resource id for the SVG sprite (symbols referenced via &lt;use href="...#id"&gt;). */
    SPRITE_RESOURCE_ID: "myapp/icons/lucide-sprite.svg",

    /** Kebab-case symbol ids present in the sprite. */
    SYMBOL_IDS: [
  "menu",
  "users",
  "layout-grid",
  "printer",
  "sparkles",
  "log-out",
  "chevron-left",
  "chevron-right",
  "user",
  "mail",
  "book-text",
  "table",
  "message-circle",
  "moon",
  "x"
]
  }
});
